Add team tab in settings
giselles-ai/giselle pull request #122
Opened 2024-11-25 07:00 UTC by gentamura

## Summary
Added a link to the Team tab and its corresponding destination page in the Settings screen.

## Related Issue
None.

## Changes
- Added a Team link to the Settings screen.
- Created a Team page component and related placeholder components.

## Testing
None.

## Other Information
This is an initial implementation to support future development.

2024-11-25 07:08 UTC, gentamura commented
@satococoa Please review 🙏

2024-11-25 07:42 UTC, satococoa requested changes
Thank you for your implementation 👍 
I've added some comments. Could you please review them? 🙏

2024-11-25 07:42 UTC, satococoa commented on flags.ts
> +		return takeLocalEnv("FREE_PLAN_FLAG");
Please add this flag to `.env.example` for easier development setup.

https://github.com/giselles-ai/giselle/blob/0f1f235457fb18e2125e611406fb081ec0fb4d14/.env.example#L4-L7

2024-11-25 07:42 UTC, satococoa commented on app/(main)/settings/team/components/agent-time-usage.tsx
Thank you for implementation.
However I would like to defer adding these components until they are really needed, for the following reasons:

1. I prefer to avoid committing code with mock data at this stage
2. To keep the code review process more focused and manageable
3. For the base-button component, customizing the existing components/ui/button to ensure seamless integration with other parts of the application may be better

Would you be agreeable to this approach of adding these components later when necessary?

2024-11-26 07:24 UTC, toyamarinyon approved these changes

2024-11-27 01:22 UTC, gentamura commented
@satococoa I have corrected the codes that were noted. Please check again 🙏

2024-11-27 01:24 UTC, satococoa approved these changes
Thank you!!

2024-11-27 01:24 UTC, satococoa commented on .env.example
> +FREE_PLAN_FLAG="true
👍

2024-11-27 02:01 UTC, gentamura commented on .env.example
> +FREE_PLAN_FLAG="true
I fixed here 👉️ [88dd48a](https://github.com/giselles-ai/giselle/pull/122/commits/88dd48a5319f81833c47f5af92deaad90719412a)

2024-11-27 02:02 UTC, gentamura commented
@shige review, please 🙏

2024-11-27 02:03 UTC, satococoa commented on .env.example
> +FREE_PLAN_FLAG="true
oh..I've missed.

2024-11-27 03:18 UTC, shige approved these changes
LGTM! 👍

2024-11-27 06:15 UTC, gentamura commented
Thank you for reviewers 🚀

2024-11-27 06:15 UTC, merged